import type { Producto } from '../tipos/producto'

export const catalogo: Producto[] = [
  {
    id: 'balenciaga-tee-black',
    nombre: 'Balenciaga Tee — Rayas',
    marca: 'BALENCIAGA',
    categoria: 'remeras',
    precio: 8900,
    descripcion: 'Remera oversized negra. Rayas rojas en mangas. Logo bordado en pecho. 100% algodón pesado.',
    talles: [
      { talle: 'S', estado: 'agotado' },
      { talle: 'M', estado: 'disponible' },
      { talle: 'L', estado: 'disponible' },
      { talle: 'XL', estado: 'pocas-unidades' },
    ],
    etiquetas: ['balenciaga', 'oversized', 'rayas'],
    esNuevo: true,
    dropNumero: 2,
    colorPlaceholder: '#0d0d0d',
    foto: '/productos/balenciaga-tee-black.jpg',
  },
  {
    id: 'emotion-tee',
    nombre: 'Emotion Tee — Allover',
    marca: 'EMOTION',
    categoria: 'remeras',
    precio: 6400,
    descripcion: 'Remera blanca con gráfico allover serigrafía. Ángel en relieve. Edición limitada.',
    talles: [
      { talle: 'S', estado: 'disponible' },
      { talle: 'M', estado: 'pocas-unidades' },
      { talle: 'L', estado: 'disponible' },
      { talle: 'XL', estado: 'agotado' },
    ],
    etiquetas: ['emotion', 'gráfica', 'allover', 'limitado'],
    esNuevo: true,
    dropNumero: 2,
    colorPlaceholder: '#1a1a1a',
    foto: '/productos/emotion-tee.jpg',
  },
  {
    id: 'balenciaga-hoodie-paris',
    nombre: 'Balenciaga Hoodie — Paris',
    marca: 'BALENCIAGA',
    categoria: 'buzos',
    precio: 14500,
    descripcion: 'Hoodie negro Balenciaga Paris. Logo collegiate en pecho. Fleece pesado. Fit oversized.',
    talles: [
      { talle: 'S', estado: 'disponible' },
      { talle: 'M', estado: 'disponible' },
      { talle: 'L', estado: 'pocas-unidades' },
      { talle: 'XL', estado: 'agotado' },
    ],
    etiquetas: ['balenciaga', 'paris', 'hoodie', 'fleece'],
    esNuevo: true,
    dropNumero: 2,
    colorPlaceholder: '#0a0a0a',
    foto: '/productos/balenciaga-hoodie-paris.jpg',
  },
  {
    id: 'essential-tee',
    nombre: 'Essential Tee',
    marca: 'FOCUS BASICS',
    categoria: 'remeras',
    precio: 1490,
    descripcion: 'Remera de algodón 220g. Fit oversized. Cuello redondo reforzado.',
    talles: [
      { talle: 'S', estado: 'agotado' },
      { talle: 'M', estado: 'disponible' },
      { talle: 'L', estado: 'disponible' },
      { talle: 'XL', estado: 'pocas-unidades' },
    ],
    etiquetas: ['básica', 'oversized', 'algodón'],
    esNuevo: false,
    colorPlaceholder: '#1a1a1a',
  },
  {
    id: 'arch-logo-hoodie',
    nombre: 'Arch Logo Hoodie',
    marca: 'FOCUS DROP 02',
    categoria: 'buzos',
    precio: 3200,
    descripcion: 'Buzo canguro. Fleece 380g. Logo arco en pecho. Cordones planos.',
    talles: [
      { talle: 'S', estado: 'disponible' },
      { talle: 'M', estado: 'disponible' },
      { talle: 'L', estado: 'agotado' },
      { talle: 'XL', estado: 'agotado' },
    ],
    etiquetas: ['hoodie', 'fleece', 'logo'],
    esNuevo: false,
    dropNumero: 2,
    colorPlaceholder: '#0f0f0f',
  },
  {
    id: 'bucket-hat',
    nombre: 'Bucket Hat',
    marca: 'FOCUS ACCS',
    categoria: 'accesorios',
    precio: 1150,
    descripcion: 'Sombrero tipo pescador. Ripstop doble capa. Fit medio.',
    talles: [{ talle: 'unico', estado: 'disponible' }],
    etiquetas: ['bucket', 'ripstop', 'streetwear'],
    esNuevo: false,
    colorPlaceholder: '#111111',
  },
  {
    id: 'wide-cargo',
    nombre: 'Wide Cargo',
    marca: 'FOCUS DROP 02',
    categoria: 'pantalones',
    precio: 4100,
    descripcion: 'Cargo de corte ancho. Twill 300g. Seis bolsillos. Sin tabas.',
    talles: [
      { talle: 'S', estado: 'disponible' },
      { talle: 'M', estado: 'pocas-unidades' },
      { talle: 'L', estado: 'disponible' },
      { talle: 'XL', estado: 'disponible' },
    ],
    etiquetas: ['cargo', 'wide leg', 'twill'],
    esNuevo: false,
    dropNumero: 2,
    colorPlaceholder: '#0a0a0a',
  },
  {
    id: 'graphic-tee-01',
    nombre: 'Graphic Tee 01',
    marca: 'FOCUS DROP 01',
    categoria: 'remeras',
    precio: 1890,
    descripcion: 'Remera con gráfico serigrafía al agua. Edición limitada Drop 01.',
    talles: [
      { talle: 'S', estado: 'agotado' },
      { talle: 'M', estado: 'agotado' },
      { talle: 'L', estado: 'agotado' },
    ],
    etiquetas: ['gráfica', 'serigrafía', 'limitado'],
    esNuevo: false,
    dropNumero: 1,
    colorPlaceholder: '#0d0d0d',
  },
]

export const categorias = [
  { valor: 'todo' as const, etiqueta: 'TODO' },
  { valor: 'remeras' as const, etiqueta: 'REMERAS' },
  { valor: 'buzos' as const, etiqueta: 'BUZOS' },
  { valor: 'pantalones' as const, etiqueta: 'PANTALONES' },
  { valor: 'accesorios' as const, etiqueta: 'ACCESORIOS' },
] as const

export type FiltroCategoria = (typeof categorias)[number]['valor']
